version: '3.5'

services:
  api:
    image: dainst/image-processing-api
    build:
      context: ./service
    ports:
      - '5001:5000'
    volumes:
    #- ./service:/service
      - ./projects:/projects
   
    working_dir: /service
  ui:
    image: dainst/image-processing-ui
    build:
      context: ./frontend
    ports:
      - '8080:80'
