version: '3.5'

services:
  results-db:
    container_name: image_processing_db
    build:
      context: db
    ports:
      - '3308:3306'
    volumes:
      - "data:/var/lib/mysql"

volumes:
  data: {}
