version: '3.5'

services:
  api:
    image: dainst/image-processing-api
    build:
      context: ./service
    ports:
      - '5000:5000'
    volumes:
      - ./projects:/projects
      - ${LOCAL_IMAGE_DIR}:/images
    working_dir: /service    
    restart: ${RESTART_POLICY}

