version: '3.5'

services:
  results-db:
    container_name: image_processing_db
    build:
      context: db
    ports:
      - '3308:3306'
    volumes:
      - ./db_data/mysql:/var/lib/mysql
    networks:
      - network_1

  service-backend:
    container_name: image_service_backend
    build:
      context: ./service
    environment:
      PYTHONPATH: /service:/libs
    ports:
      - "5000:5000"
    volumes:
      - ./service:/service
      - ./db:/libs/db
    working_dir: /service
    depends_on:
      - results-db
    networks:
      - network_1

networks:
  network_1:
    name: 'image_processing'
    driver: bridge
    ipam:
        config:
        - subnet: 192.168.18.1/24
