version: '3.5'

services:
  flask:
    container_name: image_processing_service
    build:
      context: ./service
    ports:
      - "5000:5000"
    volumes:
      - ./service:/service
      - ./projects:/projects
      - /home/shohl/Bilder/preliminary:/images/max_haibt
      - /home/shohl/Bilder/idai_cloud_auswahl:/images/idai_cloud_auswahl
    working_dir: /service
    restart: ${RESTART_POLICY}
